apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: kube-system
  name: juju-credential-microk8s
  labels:
    juju-credential: microk8s
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
- nonResourceURLs: ["*"]
  verbs: ["*"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: kube-system
  name: juju-credential-microk8s
  labels:
    juju-credential: microk8s
secrets:
- kind: Secret
  name: juju-credential-microk8s
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  namespace: kube-system
  name: juju-credential-microk8s
  labels:
    juju-credential: microk8s
subjects:
- kind: ServiceAccount
  name: juju-credential-microk8s
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: juju-credential-microk8s
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  namespace: kube-system
  name: juju-credential-microk8s
  labels:
    juju-credential: microk8s
  annotations:
    kubernetes.io/service-account.name: juju-credential-microk8s
type: kubernetes.io/service-account-token
