---
version: 0.1.0
extraKubeletArgs:
  --cluster-domain: cluster.local
  --cluster-dns: 10.152.183.10
addons:
  - name: dns
containerdRegistryConfigs:
  docker.io: |
    [host."https://docker-cache.us-west-2.aws.jujuqa.com:443"]
      capabilities = ["pull", "resolve"]
  10.152.183.69: |
    [host."https://10.152.183.69:443"]
      capabilities = ["pull", "resolve", "push"]
      skip_verify = true
  
