name: "Snapcraft"
on:
  push:
    branches: [2.9, 3.1, 3.2, 3.3, main]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - '**.go'
      - 'go.mod'
      - 'snap/**'
      - '.github/workflows/snap.yml'
  workflow_dispatch:
permissions:
  contents: read

jobs:

  snap:
    name: linux-arm64
    runs-on: [self-hosted, linux, arm64, aws, large]
    if: github.event.pull_request.draft == false
    steps:

    - name: Install Dependencies
      shell: bash
      run: |
        set -euxo pipefail
        sudo snap install snapcraft --classic
        echo "/snap/bin" >> $GITHUB_PATH

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup LXD
      uses: canonical/setup-lxd@90d76101915da56a42a562ba766b1a77019242fd

    - name: Set up Go
      if: env.RUN_TEST == 'RUN'
      uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'
        cache: true

    - name: Build snap
      shell: bash
      run: |
        set -euxo pipefail
        snapcraft --use-lxd

    - name: Install snap
      shell: bash
      run: |
        set -euxo pipefail
        sudo snap install *.snap --dangerous --classic

    - name: Test bootstrap
      shell: bash
      run: |
        set -euxo pipefail
        juju bootstrap localhost
